clean_path = [
  "snow_overrides/brand_overrides",
  "out/Release/gen/snow_overrides/build",
]

sign_server = "10.2.0.47:10839"

oem = [
  "normal",
  "nuctech",
  ""
]

[git]
addr = "ssh://10.0.10.15:29418/108.0.5359.215"

[src]
windows = "G:/snow_108_pkg/108.0.5359.215"
linux = "/home/snowtech/code/code/108.0.5359.215"
macos = "/Users/snow/code/git/108.0.5359.215"
db = "backup.db"

[dev_tools]
windows = "E:/snow_commit/dev_tools"
linux = "/home/snowtech/code/132/source/depot_tools"
macos = "/Users/snow/code/git/dev_tools"

[python]
linux = "/home/snowtech/code/132/source/depot_tools/python-bin"
macos = "/Users/snow/code/git/dev_tools/python-bin"


[backup_path]
windows = "E:/snow_commit/backup"
linux = "/home/snowtech/backup"
macos = "/Users/snow/backup"

[server]
windows = ["10.0.10.14:3000"]
macos = ["10.0.80.38:3000"]
linux = ["10.2.0.239:3000"]

[email]
web = "10.0.10.14:3000"
smtp = "smtp.163.com"
from = "ccjuuc@163.com"
password = "BVjEVanDF2jwbWjF"
to = [
  "ccjuuc@163.com",
  "shangzhijie@snowtech.com.cn"
]


[gn_default_args]
windows = [
  "is_debug=false",
  "is_component_build=false",
  "is_clang=true",
  "is_official_build=true"
]
linux = [
  "grpc_use_static_linking=true",
  "is_official_build=true",
  "symbol_level=1",
  "blink_symbol_level=1",
  "is_clang=true",
]
macos = [
  "use_system_xcode=true",
  "is_debug=false",
  "is_component_build=false",
  "is_clang=true",
  "is_official_build=true"
]
